name: Build & Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  SERVICE_NAME: bookmanager
  REGION: europe-west8
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPO: apps

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build & Push image
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          gcloud artifacts repositories create ${{ env.REPO }} --repository-format=docker --location=${{ env.REGION }} --description="App containers" || true
          gcloud builds submit --tag "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }}             --image "$IMAGE"             --region ${{ env.REGION }}             --allow-unauthenticated             --add-cloudsql-instances ${{ secrets.DB_INSTANCE_CONNECTION_NAME }}             --set-env-vars SPRING_PROFILES_ACTIVE=prod,GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }},GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }},DB_INSTANCE_CONNECTION_NAME=${{ secrets.DB_INSTANCE_CONNECTION_NAME }},DB_NAME=${{ secrets.DB_NAME }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }}
